name: flutter_application
description: Ежедневные цитаты — красиво и легко

environment:
  sdk: ">=2.18.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_spinkit: ^5.2.0
  cached_network_image: ^3.2.3
  share_plus: ^7.0.0
  shared_preferences: ^2.1.1
  palette_generator: ^0.3.2
  google_fonts: ^5.0.0
  flutter_cache_manager: ^3.3.1
  url_launcher: ^6.3.1
  just_audio: ^0.9.36
  lottie: ^3.3.1
  scrollable_positioned_list: ^0.3.8
  table_calendar: ^3.0.9
  audioplayers: ^6.0.0
  path_provider: ^2.1.1
  googleapis: ^13.2.0
  googleapis_auth: ^1.4.1
  dio: ^5.4.0
  connectivity_plus: ^5.0.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1


flutter:
  uses-material-design: true

  assets:
#Иконка
    - assets/icon/app_icon.png

#Звуки
    - assets/sounds/candle.mp3
    - assets/sounds/chime.mp3
    - assets/sounds/fire.mp3
    - assets/sounds/page_turn.mp3
    - assets/sounds/theme_greece_ambient.mp3
    - assets/sounds/theme_nordic_ambient.mp3
    - assets/sounds/theme_pagan_ambient.mp3
    - assets/sounds/theme_philosophy_ambient.mp3
    - assets/sounds/theme_philosophy_open.mp3
    - assets/sounds/theme_nordic_open.mp3
    - assets/sounds/theme_greece_open.mp3
    - assets/sounds/theme_pagan_open.mp3
    - assets/sounds/breath.mp3
#Картинки
    - assets/images/book_background.jpg
    - assets/images/greece.jpg
    - assets/images/nordic.jpg
    - assets/images/pagan.jpg
    - assets/images/philosophy.jpg
    - assets/images/rune_icon.png
    - assets/images/rune_icon_small.png
    - assets/icon/old1.png
#Не рабочие анимации
    - assets/animations/fire.gif
    - assets/animations/greece.json
    - assets/animations/nordic.json
    - assets/animations/pagan.json
    - assets/animations/philosophy.json
#Текста

    - assets/full_texts/nordic/
    - assets/full_texts/pagan/
    - assets/full_texts/philosophy/
    - assets/full_texts/greece/
    - assets/config/book_sources.json

#Аудиокниги
    - assets/audiobooks/eliade_sacred_profane/chapter_01_part_01.mp3
    - assets/audiobooks/eliade_sacred_profane/chapter_01_part_02.mp3
    - assets/config/audiobooks.json
    - assets/full_texts/greece/aristotle/metaphysics_raw.txt
    - assets/full_texts/greece/aristotle/metaphysics_cleaned.txt
    - assets/full_texts/greece/aristotle/ethics_raw.txt
    - assets/full_texts/greece/aristotle/ethics_cleaned.txt
    - assets/full_texts/greece/aristotle/politics_raw.txt
    - assets/full_texts/greece/aristotle/politics_cleaned.txt
    - assets/full_texts/greece/aristotle/rhetoric_raw.txt
    - assets/full_texts/greece/aristotle/rhetoric_cleaned.txt
    - assets/full_texts/greece/plato/sophist_raw.txt
    - assets/full_texts/greece/plato/sophist_cleaned.txt
    - assets/full_texts/greece/plato/parmenides_raw.txt
    - assets/full_texts/greece/plato/parmenides_cleaned.txt
    - assets/full_texts/greece/homer/iliad_raw.txt
    - assets/full_texts/greece/homer/iliad_cleaned.txt
    - assets/full_texts/greece/homer/odyssey_raw.txt
    - assets/full_texts/greece/homer/odyssey_cleaned.txt
    - assets/full_texts/greece/hesiod/labour_and_days_raw.txt
    - assets/full_texts/greece/hesiod/labour_and_days_cleaned.txt
    - assets/full_texts/nordic/folk/beowulf_raw.txt
    - assets/full_texts/nordic/folk/beowulf_cleaned.txt
    - assets/full_texts/nordic/folk/elder_edda_raw.txt
    - assets/full_texts/nordic/folk/elder_edda_cleaned.txt
    - assets/full_texts/nordic/folk/elder_edda_raw.txt
    - assets/full_texts/nordic/folk/elder_edda_cleaned.txt
    - assets/full_texts/philosophy/heidegger/being_and_time_raw.txt
    - assets/full_texts/philosophy/heidegger/being_and_time_cleaned.txt
    - assets/full_texts/philosophy/heidegger/what_means_to_think_raw.txt
    - assets/full_texts/philosophy/heidegger/what_means_to_think_cleaned.txt
    - assets/full_texts/philosophy/nietzsche/antichrist_raw.txt
    - assets/full_texts/philosophy/nietzsche/antichrist_cleaned.txt
    - assets/full_texts/philosophy/nietzsche/gay_science_raw.txt
    - assets/full_texts/philosophy/nietzsche/gay_science_cleaned.txt
    - assets/full_texts/philosophy/nietzsche/thus_spoke_zarathustra_raw.txt
    - assets/full_texts/philosophy/nietzsche/thus_spoke_zarathustra_cleaned.txt
    - assets/full_texts/philosophy/nietzsche/birth_of_tragedy_raw.txt
    - assets/full_texts/philosophy/nietzsche/birth_of_tragedy_cleaned.txt
    - assets/full_texts/philosophy/nietzsche/beyond_good_and_evil_raw.txt
    - assets/full_texts/philosophy/nietzsche/beyond_good_and_evil_cleaned.txt
    - assets/full_texts/philosophy/schopenhauer/world_as_will_and_representation_raw.txt
    - assets/full_texts/philosophy/schopenhauer/world_as_will_and_representation_cleaned.txt
    - assets/full_texts/philosophy/schopenhauer/aphorisms_on_wisdom_of_life_raw.txt
    - assets/full_texts/philosophy/schopenhauer/aphorisms_on_wisdom_of_life_cleaned.txt
    - assets/full_texts/pagan/de_benua/on_being_a_pagan_raw.txt
    - assets/full_texts/pagan/de_benua/on_being_a_pagan_cleaned.txt
    - assets/full_texts/pagan/mercea_eliade/history_of_religious_ideas_vol1_raw.txt
    - assets/full_texts/pagan/mercea_eliade/history_of_religious_ideas_vol1_cleaned.txt
    - assets/full_texts/pagan/mercea_eliade/history_of_religious_ideas_vol2_raw.txt
    - assets/full_texts/pagan/mercea_eliade/history_of_religious_ideas_vol2_cleaned.txt
    - assets/full_texts/pagan/mercea_eliade/history_of_religious_ideas_vol3_raw.txt
    - assets/full_texts/pagan/mercea_eliade/history_of_religious_ideas_vol3_cleaned.txt
    - assets/full_texts/pagan/julius_evola/pagan_imperialism_raw.txt
    - assets/full_texts/pagan/julius_evola/pagan_imperialism_cleaned.txt
    - assets/full_texts/pagan/julius_evola/metaphysics_of_sex_raw.txt
    - assets/full_texts/pagan/julius_evola/metaphysics_of_sex_cleaned.txt
    - assets/full_texts/pagan/julius_evola/men_among_ruins_raw.txt
    - assets/full_texts/pagan/julius_evola/men_among_ruins_cleaned.txt
    - assets/full_texts/pagan/mercea_eliade/sacred_and_profane_raw.txt
    - assets/full_texts/pagan/mercea_eliade/sacred_and_profane_cleaned.txt
    - assets/full_texts/pagan/mercea_eliade/myth_of_eternal_return_raw.txt
    - assets/full_texts/pagan/mercea_eliade/myth_of_eternal_return_cleaned.txt
    - assets/curated/my_quotes_approved.json
    - assets/full_texts/pagan/askr_svarte/pagan_identity_xxi_raw.txt
    - assets/full_texts/pagan/askr_svarte/pagan_identity_xxi_cleaned.txt
    - assets/full_texts/pagan/askr_svarte/priblizheniye_i_okruzheniye_raw.txt
    - assets/full_texts/pagan/askr_svarte/priblizheniye_i_okruzheniye_cleaned.txt
    - assets/full_texts/pagan/askr_svarte/polemos_raw.txt
    - assets/full_texts/pagan/askr_svarte/polemos_cleaned.txt



flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/icon/app_icon.png"  # путь к твоей PNG-иконке